<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.javaguns.roses</groupId>
        <artifactId>kernel-o-monitor</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>monitor-spring-boot-starter</artifactId>

    <packaging>jar</packaging>

    <name>monitor-spring-boot-starter</name>
    <description>系统监控模块的自动配置</description>

    <dependencies>

        <!--系统监控-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>monitor-business-system-info</artifactId>
            <version>${roses.version}</version>
        </dependency>

    </dependencies>

</project>
