<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.javaguns.roses</groupId>
        <artifactId>kernel-o-monitor</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>monitor-business-system-info</artifactId>

    <packaging>jar</packaging>

    <name>monitor-business-system-info</name>
    <description>系统监控，获取系统信息的实现</description>

    <dependencies>

        <!--监控模块的的api-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>monitor-api</artifactId>
            <version>${roses.version}</version>
        </dependency>

        <!--定时任务的api-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>timer-api</artifactId>
            <version>${roses.version}</version>
        </dependency>

        <!--硬件信息获取-->
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>${oshi.version}</version>
        </dependency>

        <!--资源api模块-->
        <!--用在资源控制器，资源扫描上-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>scanner-api</artifactId>
            <version>${roses.version}</version>
        </dependency>

        <!--web模块-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

    </dependencies>

</project>
