<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.javaguns.roses</groupId>
        <artifactId>kernel-s-user-favorite</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>user-favorite-spring-boot-starter</artifactId>

    <packaging>jar</packaging>

    <name>user-favorite-spring-boot-starter</name>
    <description>用户收藏模块的自动配置</description>

    <dependencies>

        <!--用户收藏业务模块-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>user-favorite-business</artifactId>
            <version>${revision}</version>
        </dependency>   

    </dependencies>

</project>
