<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.javaguns.roses</groupId>
        <artifactId>kernel-s-system</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>system-api</artifactId>

    <packaging>jar</packaging>

    <name>system-api</name>
    <description>系统管理基础API</description>

    <dependencies>

        <!--config模块的api-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>config-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <!--参数校验模块-->
        <!--用在控制器，参数校验-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>validator-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <!--scanner模块api-->
        <!--需要用的resource相关的pojo-->
        <dependency>
            <groupId>com.javaguns.roses</groupId>
            <artifactId>scanner-api</artifactId>
            <version>${revision}</version>
        </dependency>

        <!--web-->
        <!--UserInfoRemoteApi会用到web，用在提供feign接口时-->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

    </dependencies>

</project>
